### ISSUE TITLE
[Fonctionnalité] Ajouter un lien stable ou latest

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki-build-repo#7]
Bonjour,

Dans un soucis d'automatisation, j'ai régulièrement besoin de récupérer la dernière release. Actuellement je dois aller chercher le nom de la dernière release sur yeswiki.net et le changer dans mes scripts. Avec un lien "latest" ou "stable" ça permettrai d'éviter cette étape et d'installer toujours la dernière version sans prise de tête.
De plus, il ne serait plus nécessaire de mettre à jour le lien sur le site YesWiki (je suppose que c'est ce qui se fait actuellement).

Exemple : https://repository.yeswiki.net/cercopitheque/latest.zip

Il ne me semble pas que ce soit compliqué a ajouter et je ne serais sûrement pas le seul à qui cela servira.

**Comment by mrflos** [comment]
Pour les versions sur le sites de yeswiki, on parse le json pour avoir le bon numéro de version, comme ca pas besoin que changer les liens a chaque changement de version!    
Je ne suis pas contre rajouter un lien symbolique vers latest.zip, mais je suis plutot en train de prendre la direction inverse, et plutot gerer les versions avec des tags semver.  
Mais l'un n'empêchera pas l'autre, juste on ma fait remarquer avec raison qu'il faudra qu'une commande de build reproduise toujours le meme résultat avec des version identifiables. Dans le cas d'un zip latest il sera changeant avec le temps.

**Comment by fbredow** [comment]
Justement pas un zip, juste un lien symbolique vers la dernière archive. Ça reste compatible avec des tags semvers :) et effectivement c'est une bonne idée que les résultat du build soit toujours identique avec un même tag.

je peux tenter de proposer une pull request dans la semaine.

**Comment by mrflos** [comment]
c'est fait dans la dernière version, cf. https://repository.yeswiki.net/doryphore/ mais il y a d'autres changements :

- les builds sont générés à partir de la source git plutôt que le zip de github (cela permettra d'intégrer des dépôts hors de github, comme framagit, gitlab, etc..)
- on peut utiliser les tags git pour avoir une version en particulier
- les numéros de version sont calculé avec git log : date du git + numéro de commit dans la journée si plusieurs
- le fichier de conf des repo a changé : il prend les url de dépôt git plutôt que les archives zip cf. https://github.com/YesWiki/yeswiki-config-repo/blob/master/repo.config.json
